"""MultiQC custom-content export helpers."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from dicomqc.model.results import ScanResult, Severity

PARENT_SECTION = {
    "parent_id": "dicomqc",
    "parent_name": "dicomqc",
    "parent_description": "DICOM metadata quality-control summaries generated by dicomqc.",
}


def write_multiqc(result: ScanResult, output_dir: Path) -> Path:
    """Write a MultiQC custom-content directory and return its path."""

    if output_dir.suffix.lower() in {".yaml", ".yml"}:
        raise ValueError(f"dicomqc writes MultiQC custom content as a directory, not a YAML file: {output_dir}")
    output_dir.mkdir(parents=True, exist_ok=True)
    _clear_existing_bundle(output_dir)
    _write_text(output_dir, "dicomqc_00_overview_mqc.html", build_overview_html(result))
    _write_yaml(output_dir, "dicomqc_summary_mqc.yaml", build_summary_payload(result))
    _write_yaml(output_dir, "dicomqc_01_release_status_mqc.yaml", build_release_status_payload(result))
    _write_yaml(output_dir, "dicomqc_02_findings_mqc.yaml", build_findings_payload(result))
    return output_dir


def build_overview_html(result: ScanResult) -> str:
    if result.error_count or result.skipped_files:
        status = "blocked"
        status_label = "Blocked"
        status_note = "Release is blocked until error findings or unreadable files are resolved."
    elif result.warning_count:
        status = "review"
        status_label = "Review"
        status_note = "No blocking errors were found, but warnings require documented review."
    else:
        status = "pass"
        status_label = "Pass"
        status_note = "No blocking findings were detected by the active dicomqc policy."

    return f"""<!--
id: dicomqc_00_overview
parent_id: dicomqc
parent_name: dicomqc
parent_description: DICOM metadata quality-control summaries generated by dicomqc.
section_name: dicomqc audit overview
description: At-a-glance release-readiness summary for the scanned DICOM candidate dataset.
plot_type: html
-->
<div class="dicomqc-dashboard dicomqc-status-{status}">
  <div class="dicomqc-status-card">
    <span class="dicomqc-label">Release status</span>
    <strong>{status_label}</strong>
    <p>{status_note}</p>
  </div>
  <div class="dicomqc-metrics">
    <div><span>{result.files_scanned}</span><small>DICOM files</small></div>
    <div><span>{result.error_count}</span><small>Errors</small></div>
    <div><span>{result.warning_count}</span><small>Warnings</small></div>
    <div><span>{len(result.skipped_files)}</span><small>Skipped</small></div>
  </div>
</div>
"""


def build_summary_payload(result: ScanResult) -> dict[str, Any]:
    data = {
        "dicomqc": {
            "files_scanned": result.files_scanned,
            "errors": result.error_count,
            "warnings": result.warning_count,
            "skipped_files": len(result.skipped_files),
            "private_tag_findings": sum(1 for finding in result.findings if finding.keyword == "PrivateTags"),
        }
    }
    headers = {
        "files_scanned": {
            "title": "DICOM files",
            "description": "DICOM files successfully scanned",
            "scale": "Blues",
        },
        "errors": {
            "title": "dicomqc errors",
            "description": "Validation errors reported by dicomqc",
            "scale": "Reds",
        },
        "warnings": {
            "title": "dicomqc warnings",
            "description": "Warnings reported by dicomqc",
            "scale": "YlOrBr",
        },
        "skipped_files": {
            "title": "Skipped files",
            "description": "Files that could not be read as DICOM",
            "scale": "Purples",
        },
        "private_tag_findings": {
            "title": "Private tag files",
            "description": "Files with private-tag findings",
            "scale": "Oranges",
        },
    }
    return _section_payload(
        "dicomqc_summary",
        "dicomqc summary",
        "dicomqc metadata validation summary for MultiQC general statistics.",
        "generalstats",
        data,
        headers=headers,
    )


def build_findings_payload(result: ScanResult) -> dict[str, Any]:
    rows = {
        f"finding_{index:03d}": {
            "file": finding.path,
            "severity": finding.severity.value,
            "rule_id": finding.rule_id,
            "tag": finding.tag or "",
            "keyword": finding.keyword or "",
            "value_state": finding.value_state.value,
            "message": finding.message,
        }
        for index, finding in enumerate(result.findings, start=1)
        if finding.severity in {Severity.ERROR, Severity.WARNING}
    }
    return _section_payload(
        "dicomqc_02_findings",
        "dicomqc findings requiring review",
        "Redaction-safe dicomqc warnings and errors. Values are never shown in this table.",
        "table",
        rows,
        pconfig={"id": "dicomqc_findings_table", "title": "dicomqc findings requiring review"},
        headers={
            "severity": {
                "title": "Severity",
                "description": "dicomqc finding severity",
                "bgcols": {"error": "#dc2626", "warning": "#f59e0b"},
            },
            "file": {"title": "File", "description": "Relative DICOM file path", "scale": False},
            "keyword": {"title": "Keyword", "description": "DICOM keyword or finding group"},
            "tag": {"title": "Tag", "description": "DICOM tag when applicable"},
            "value_state": {
                "title": "Value state",
                "description": "Redaction-safe value state",
                "bgcols": {"present": "#f97316", "empty": "#94a3b8", "absent": "#22c55e"},
            },
            "rule_id": {"title": "Rule", "description": "Stable dicomqc rule identifier", "scale": False},
            "message": {"title": "Finding", "description": "Finding summary", "scale": False},
        },
    )


def build_release_status_payload(result: ScanResult) -> dict[str, Any]:
    if result.error_count or result.skipped_files:
        status = "blocked"
    elif result.warning_count:
        status = "review"
    else:
        status = "pass"
    data = {
        "dicomqc": {
            "Status": status,
            "Profile": result.profile_id,
            "Files scanned": result.files_scanned,
            "Files passed": result.files_passed,
            "Files failed": result.files_failed,
            "Errors": result.error_count,
            "Warnings": result.warning_count,
            "Skipped files": len(result.skipped_files),
        }
    }
    return _section_payload(
        "dicomqc_01_release_status",
        "dicomqc audit status",
        "Compact release-readiness status for the scanned DICOM candidate dataset.",
        "table",
        data,
        pconfig={"id": "dicomqc_release_status_table", "title": "dicomqc release status"},
        headers={
            "Status": {
                "title": "Status",
                "description": "pass, review, or blocked",
                "bgcols": {"pass": "#16a34a", "review": "#f59e0b", "blocked": "#dc2626"},
            },
            "Profile": {"title": "Profile", "description": "dicomqc profile used for the audit", "scale": False},
            "Files scanned": {"title": "Scanned", "description": "DICOM files successfully scanned", "scale": "Blues"},
            "Files passed": {"title": "Passed", "description": "Scanned files without error findings", "scale": "Greens"},
            "Files failed": {"title": "Failed", "description": "Scanned files with error findings", "scale": "Reds"},
            "Errors": {"title": "Errors", "description": "Blocking dicomqc findings", "scale": "Reds"},
            "Warnings": {"title": "Warnings", "description": "Findings requiring review", "scale": "YlOrBr"},
            "Skipped files": {
                "title": "Skipped",
                "description": "Files that could not be read as DICOM",
                "scale": "Purples",
            },
        },
    )


def _section_payload(
    section_id: str,
    section_name: str,
    description: str,
    plot_type: str,
    data: Any,
    *,
    pconfig: dict[str, Any] | None = None,
    headers: dict[str, Any] | None = None,
) -> dict[str, Any]:
    payload = {
        "id": section_id,
        **PARENT_SECTION,
        "section_name": section_name,
        "description": description,
        "plot_type": plot_type,
        "data": data,
    }
    if pconfig is not None:
        payload["pconfig"] = pconfig
    if headers is not None:
        payload["headers"] = headers
    return payload


def _write_yaml(output_dir: Path, filename: str, payload: dict[str, Any]) -> Path:
    output = output_dir / filename
    output.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")
    return output


def _write_text(output_dir: Path, filename: str, content: str) -> Path:
    output = output_dir / filename
    output.write_text(content, encoding="utf-8")
    return output


def _clear_existing_bundle(output_dir: Path) -> None:
    for pattern in ("*_mqc.yaml", "*_mqc.html"):
        for path in output_dir.glob(pattern):
            if path.is_file():
                path.unlink()
