"""MultiQC custom-content export helpers."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from dicomqc.model.results import ScanResult, Severity

DICOMQC_PARENT = {
    "parent_id": "dicomqc",
    "parent_name": "DICOMQC",
    "parent_description": "DICOM metadata quality-control summaries generated by DICOMQC.",
}


def write_multiqc(result: ScanResult, output_dir: Path) -> Path:
    """Write a MultiQC custom-content directory and return its path."""

    output_dir.mkdir(parents=True, exist_ok=True)
    _write_yaml(output_dir, "dicomqc_summary_mqc.yaml", build_summary_payload(result))
    _write_yaml(output_dir, "dicomqc_findings_mqc.yaml", build_findings_payload(result))
    return output_dir


def build_summary_payload(result: ScanResult) -> dict[str, Any]:
    data = {
        "DICOMQC": {
            "files_scanned": result.files_scanned,
            "errors": result.error_count,
            "warnings": result.warning_count,
            "skipped_files": len(result.skipped_files),
            "private_tag_findings": sum(1 for finding in result.findings if finding.keyword == "PrivateTags"),
        }
    }
    headers = {
        "files_scanned": {"title": "DICOM files", "description": "DICOM files successfully scanned"},
        "errors": {"title": "DICOMQC errors", "description": "Validation errors reported by DICOMQC"},
        "warnings": {"title": "DICOMQC warnings", "description": "Warnings reported by DICOMQC"},
        "skipped_files": {"title": "Skipped files", "description": "Files that could not be read as DICOM"},
        "private_tag_findings": {"title": "Private tag files", "description": "Files with private-tag findings"},
    }
    return _section_payload(
        "dicomqc_summary",
        "DICOMQC summary",
        "DICOMQC metadata validation summary for MultiQC general statistics.",
        "generalstats",
        data,
        headers=headers,
    )


def build_findings_payload(result: ScanResult) -> dict[str, Any]:
    rows = [
        {
            "file": finding.path,
            "severity": finding.severity.value,
            "rule_id": finding.rule_id,
            "tag": finding.tag or "",
            "keyword": finding.keyword or "",
            "value_state": finding.value_state.value,
            "message": finding.message,
        }
        for finding in result.findings
        if finding.severity in {Severity.ERROR, Severity.WARNING}
    ]
    return _section_payload(
        "dicomqc_findings",
        "DICOMQC findings",
        "Redaction-safe DICOMQC warning and error findings.",
        "table",
        rows,
        pconfig={"id": "dicomqc_findings_table", "title": "DICOMQC findings"},
    )


def _section_payload(
    section_id: str,
    section_name: str,
    description: str,
    plot_type: str,
    data: Any,
    *,
    pconfig: dict[str, Any] | None = None,
    headers: dict[str, Any] | None = None,
) -> dict[str, Any]:
    payload = {
        "id": section_id,
        **DICOMQC_PARENT,
        "section_name": section_name,
        "description": description,
        "plot_type": plot_type,
        "data": data,
    }
    if pconfig is not None:
        payload["pconfig"] = pconfig
    if headers is not None:
        payload["headers"] = headers
    return payload


def _write_yaml(output_dir: Path, filename: str, payload: dict[str, Any]) -> Path:
    output = output_dir / filename
    output.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")
    return output
