"""MultiQC custom-content export helpers."""

from __future__ import annotations

from pathlib import Path
from html import escape
from typing import Any

import yaml

from dicomqc.model.results import ScanResult
from dicomqc.reports.status import audit_guidance, audit_status
from dicomqc.reports.vendor import VENDOR_STYLE, render_vendor_inventory
from dicomqc.reports.uid import render_uid_coverage

OVERVIEW_STYLE = """
.dicomqc-dashboard{--dq-ink:#1c2b3c;--dq-muted:#596778;--dq-line:#dce2e8;--dq-surface:#f6f7f9;font:16px/1.6 ui-sans-serif,system-ui,sans-serif;color:var(--dq-ink);background:var(--dq-surface);border:1px solid var(--dq-line);border-radius:8px;padding:26px 28px;margin:12px 0 24px}
.dicomqc-label{display:block;color:var(--dq-muted);font-size:12px;font-weight:750;letter-spacing:1.5px;text-transform:uppercase}
.dicomqc-status-card strong{display:block;font-size:32px;line-height:1.2;letter-spacing:-1px;margin:8px 0 12px}
.dicomqc-status-error strong{color:#a83d30}.dicomqc-status-warning strong{color:#805a0a}.dicomqc-status-pass strong{color:#246c54}
.dicomqc-status-card p{font-size:16px;color:var(--dq-muted);margin:0;max-width:85ch}
.dicomqc-metrics{display:flex;flex-wrap:wrap;gap:24px;margin-top:18px}.dicomqc-metrics div{display:flex;align-items:baseline;gap:8px}.dicomqc-metrics span{font-size:20px;font-weight:750}.dicomqc-metrics small{font-size:14px;color:var(--dq-muted)}
.dicomqc-dashboard details{border-top:1px solid var(--dq-line);margin-top:22px;padding-top:12px}.dicomqc-dashboard summary{cursor:pointer;color:#096d78;font-size:14px;font-weight:650}.dicomqc-dashboard details p{margin:10px 0 0;font-size:14px;color:var(--dq-muted)}
[data-bs-theme=dark] .dicomqc-dashboard{--dq-ink:#e7edf5;--dq-muted:#afbed0;--dq-line:#394b60;--dq-surface:#1e2b3b}
[data-bs-theme=dark] .dicomqc-status-error strong{color:#ffa18e}[data-bs-theme=dark] .dicomqc-status-warning strong{color:#edcd79}[data-bs-theme=dark] .dicomqc-status-pass strong{color:#8bd3a3}[data-bs-theme=dark] .dicomqc-dashboard summary{color:#80cbd2}
@media(max-width:650px){.dicomqc-dashboard{padding:20px 16px}.dicomqc-status-card strong{font-size:26px}.dicomqc-metrics{gap:14px}}
"""

PARENT_SECTION = {
    "parent_id": "dicomqc",
    "parent_name": "dicomqc",
    "parent_description": "DICOM metadata quality-control summaries generated by dicomqc.",
}


def write_multiqc(result: ScanResult, output_dir: Path) -> Path:
    """Write a MultiQC custom-content directory and return its path."""

    if output_dir.suffix.lower() in {".yaml", ".yml"}:
        raise ValueError(f"dicomqc writes MultiQC custom content as a directory, not a YAML file: {output_dir}")
    output_dir.mkdir(parents=True, exist_ok=True)
    _clear_existing_bundle(output_dir)
    _write_text(output_dir, "dicomqc_00_overview_mqc.html", build_overview_html(result))
    _write_yaml(output_dir, "dicomqc_summary_mqc.yaml", build_summary_payload(result))
    _write_yaml(output_dir, "dicomqc_01_release_status_mqc.yaml", build_release_status_payload(result))
    _write_yaml(output_dir, "dicomqc_02_findings_mqc.yaml", build_findings_payload(result))
    return output_dir


def build_overview_html(result: ScanResult) -> str:
    status_label, status = audit_status(result)
    status_note = audit_guidance(result)
    policy_meta = ""
    if result.policy is not None:
        policy_meta = (
            f'<p>Project policy: <code>{escape(result.policy["id"])}</code> · Additive checks</p>'
            f'<p>Policy SHA-256: <code style="overflow-wrap:anywhere">{escape(result.policy["sha256"])}</code></p>'
        )
    vendor_panel = (
        '<details class="vendor-panel"><summary>Scanner and private-tag inventory</summary>'
        + render_vendor_inventory(result.vendor_summary) + '</details>'
    ) if result.vendor_summary is not None else ""
    privacy_note = (
        "Vendor inventory includes observed metadata labels. Findings omit raw tag values."
        if vendor_panel else "Raw tag values are omitted."
    )

    return f"""<!--
id: dicomqc_00_overview
parent_id: dicomqc
parent_name: dicomqc
parent_description: DICOM metadata quality-control summaries generated by dicomqc.
section_name: dicomqc audit overview
description: At-a-glance metadata audit summary for the scanned DICOM dataset.
plot_type: html
-->
<style>{OVERVIEW_STYLE}{VENDOR_STYLE if vendor_panel else ""}</style>
<div class="dicomqc-dashboard dicomqc-status-{status}">
  <div class="dicomqc-status-card">
    <span class="dicomqc-label">Audit status</span>
    <strong>{status_label}</strong>
    <p>{status_note}</p>
  </div>
  <div class="dicomqc-metrics">
    <div><span>{result.files_scanned}</span><small>Files read</small></div>
    <div><span>{result.error_count}</span><small>Errors</small></div>
    <div><span>{result.warning_count}</span><small>Warnings</small></div>
    <div><span>{len(result.skipped_files)}</span><small>Unreadable files</small></div>
  </div>
  <details><summary>Audit scope and report notes</summary>
    <p>Metadata audit only. Pixels and facial features are not inspected. A passing result is not approval to share data.</p>
    <p>{privacy_note} File paths may still identify people; review reports before sharing.</p>
    {policy_meta}
    {render_uid_coverage(result.uid_checks)}
  </details>
  {vendor_panel}
</div>
"""


def build_summary_payload(result: ScanResult) -> dict[str, Any]:
    data = {
        "dicomqc": {
            "files_scanned": result.files_scanned,
            "errors": result.error_count,
            "warnings": result.warning_count,
            "skipped_files": len(result.skipped_files),
            "private_tag_findings": sum(1 for finding in result.findings if finding.keyword == "PrivateTags"),
        }
    }
    headers = {
        "files_scanned": {
            "title": "Files read",
            "description": "DICOM files successfully scanned",
            "scale": "Blues",
        },
        "errors": {
            "title": "dicomqc errors",
            "description": "Validation errors reported by dicomqc",
            "scale": "Reds",
        },
        "warnings": {
            "title": "dicomqc warnings",
            "description": "Warnings reported by dicomqc",
            "scale": "YlOrBr",
        },
        "skipped_files": {
            "title": "Unreadable files",
            "description": "Files that could not be read as DICOM",
            "scale": "Purples",
        },
        "private_tag_findings": {
            "title": "Private tag files",
            "description": "Files with private-tag findings",
            "scale": "Oranges",
        },
    }
    return _section_payload(
        "dicomqc_summary",
        "dicomqc summary",
        "dicomqc metadata validation summary for MultiQC general statistics.",
        "generalstats",
        data,
        headers=headers,
    )


def build_findings_payload(result: ScanResult) -> dict[str, Any]:
    severity_order = {"error": 0, "warning": 1, "info": 2}
    rows = {
        f"finding_{index:03d}": {
            "file": finding.path,
            "severity": finding.severity.value,
            "rule_id": finding.rule_id,
            "tag": finding.tag or "",
            "keyword": finding.keyword or "",
            "value_state": finding.value_state.value,
            "message": finding.message,
            "recommendation": finding.recommendation,
        }
        for index, finding in enumerate(sorted(result.findings, key=lambda item: severity_order[item.severity.value]), start=1)
    }
    return _section_payload(
        "dicomqc_02_findings",
        "dicomqc findings and recommended actions",
        "Metadata findings and next steps. Raw tag values are omitted. dicomqc never modifies files.",
        "table",
        rows,
        pconfig={"id": "dicomqc_findings_table", "title": "dicomqc findings and recommended actions", "col1_header": "Finding ID"},
        headers={
            "severity": {
                "title": "Severity",
                "description": "dicomqc finding severity",
                "bgcols": {"error": "#fce8e4", "warning": "#fff2cf", "info": "#dff1f2"},
            },
            "file": {"title": "File", "description": "Relative DICOM file path", "scale": False},
            "keyword": {"title": "Keyword", "description": "DICOM keyword or finding group", "hidden": True, "scale": False},
            "tag": {"title": "Tag", "description": "DICOM tag when applicable", "hidden": True, "scale": False},
            "value_state": {
                "title": "Value state",
                "hidden": True,
                "description": "Redaction-safe value state",
                "bgcols": {"present": "#f97316", "empty": "#94a3b8", "absent": "#22c55e"},
            },
            "rule_id": {"title": "Rule", "description": "Stable dicomqc rule identifier", "scale": False, "hidden": True},
            "message": {"title": "Finding", "description": "Finding summary", "scale": False},
            "recommendation": {"title": "Next step", "description": "Recommended action using external tools", "scale": False},
        },
    )


def build_release_status_payload(result: ScanResult) -> dict[str, Any]:
    # Preserve legacy bundle filenames and IDs; displayed terminology is audit-only.
    status, _ = audit_status(result)
    data = {
        "dicomqc": {
            "Status": status,
            "Profile": result.profile_id,
            "Files scanned": result.files_scanned,
            "Files passed": result.files_passed,
            "Files failed": result.files_failed,
            "Errors": result.error_count,
            "Warnings": result.warning_count,
            "Skipped files": len(result.skipped_files),
        }
    }
    return _section_payload(
        "dicomqc_01_release_status",
        "dicomqc audit status",
        "Metadata audit status, not a decision about sharing data.",
        "table",
        data,
        pconfig={"id": "dicomqc_release_status_table", "title": "dicomqc audit status", "col1_header": "Audit"},
        headers={
            "Status": {
                "title": "Status",
                "description": "Metadata audit outcome; not approval to share data",
                "bgcols": {"Checks passed": "#e2f2eb", "Warnings require review": "#fff2cf", "Errors require attention": "#fce8e4", "No readable files": "#fff2cf"},
            },
            "Profile": {"title": "Profile", "description": "dicomqc profile used for the audit", "scale": False, "hidden": True},
            "Files scanned": {"title": "Files read", "description": "DICOM files successfully scanned", "scale": "Blues"},
            "Files passed": {"title": "Without errors", "description": "Scanned files without error findings; warnings may remain", "scale": "Greens", "hidden": True},
            "Files failed": {"title": "With errors", "description": "Scanned files with error findings", "scale": "Reds", "hidden": True},
            "Errors": {"title": "Errors", "description": "Findings requiring attention", "scale": "Reds"},
            "Warnings": {"title": "Warnings", "description": "Findings requiring review", "scale": "YlOrBr"},
            "Skipped files": {
                "title": "Unreadable files",
                "description": "Files that could not be read as DICOM",
                "scale": "Purples",
            },
        },
    )


def _section_payload(
    section_id: str,
    section_name: str,
    description: str,
    plot_type: str,
    data: Any,
    *,
    pconfig: dict[str, Any] | None = None,
    headers: dict[str, Any] | None = None,
) -> dict[str, Any]:
    payload = {
        "id": section_id,
        **PARENT_SECTION,
        "section_name": section_name,
        "description": description,
        "plot_type": plot_type,
        "data": data,
    }
    if pconfig is not None:
        payload["pconfig"] = pconfig
    if headers is not None:
        payload["headers"] = headers
    return payload


def _write_yaml(output_dir: Path, filename: str, payload: dict[str, Any]) -> Path:
    output = output_dir / filename
    output.write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")
    return output


def _write_text(output_dir: Path, filename: str, content: str) -> Path:
    output = output_dir / filename
    output.write_text(content, encoding="utf-8")
    return output


def _clear_existing_bundle(output_dir: Path) -> None:
    for pattern in ("*_mqc.yaml", "*_mqc.html"):
        for path in output_dir.glob(pattern):
            if path.is_file():
                path.unlink()
